In [1]:
import requests

In [2]:
req = requests.get('https://codeforces.com/api/problemset.problems?tags=implementation')

In [3]:
import pandas as pd

In [4]:
problems = pd.DataFrame(req.json()['result']['problems'])

In [5]:
problems.head()

,contestId,index,name,type,tags,rating,points
0,1970,F3,Playing Quidditch (Hard),PROGRAMMING,[implementation],NaN,NaN
1,1970,F2,Playing Quidditch (Medium),PROGRAMMING,[implementation],NaN,NaN
2,1970,F1,Playing Quidditch (Easy),PROGRAMMING,[implementation],NaN,NaN
3,1970,A1,Balanced Shuffle (Easy),PROGRAMMING,"[implementation, sortings]",NaN,NaN
4,1969,F,Card Pairing,PROGRAMMING,"[dp, greedy, hashing, implementation]",3000.0,NaN

In [6]:
problems.isna().sum()

contestId      0
index          0
name           0
type           0
tags           0
rating        42
points       823
dtype: int64

In [7]:
problems[['contestId', 'index', 'name']].duplicated().sum()

0

In [8]:
problems['url'] = problems.apply(lambda row: f"https://codeforces.com/problemset/problem/{row['contestId']}/{row['index']}", axis=1)

In [9]:
problems.head()

,contestId,index,name,type,tags,rating,points,url
0,1970,F3,Playing Quidditch (Hard),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F3
1,1970,F2,Playing Quidditch (Medium),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F2
2,1970,F1,Playing Quidditch (Easy),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F1
3,1970,A1,Balanced Shuffle (Easy),PROGRAMMING,"[implementation, sortings]",NaN,NaN,https://codeforces.com/problemset/problem/1970/A1
4,1969,F,Card Pairing,PROGRAMMING,"[dp, greedy, hashing, implementation]",3000.0,NaN,https://codeforces.com/problemset/problem/1969/F

In [10]:
url = "https://codeforces.com/api/user.status?handle=tourist"
req = requests.get(url)

In [11]:
user = pd.DataFrame(req.json()['result'])

In [12]:
user.head()

,id,contestId,creationTimeSeconds,relativeTimeSeconds,problem,author,programmingLanguage,verdict,testset,passedTestCount,timeConsumedMillis,memoryConsumedBytes,points,pointsInfo
0,259918877,1959,1715108158,12058,"{'contestId': 1959, 'index': 'H', 'name': 'Cou...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,157,468,9113600,NaN,NaN
1,259917579,1959,1715107274,11174,"{'contestId': 1959, 'index': 'H', 'name': 'Cou...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,TIME_LIMIT_EXCEEDED,TESTS,146,2000,8089600,NaN,NaN
2,259916750,1959,1715106762,10662,"{'contestId': 1959, 'index': 'H', 'name': 'Cou...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.7,TIME_LIMIT_EXCEEDED,TESTS,146,2000,118681600,NaN,NaN
3,259915326,1959,1715105918,9818,"{'contestId': 1959, 'index': 'H', 'name': 'Cou...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,TIME_LIMIT_EXCEEDED,TESTS,146,2000,8192000,NaN,NaN
4,259913982,1959,1715105175,9075,"{'contestId': 1959, 'index': 'G', 'name': 'The...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,23,390,16179200,NaN,NaN

In [13]:
user = user[user['verdict'] == 'OK']

In [14]:
user.head()

,id,contestId,creationTimeSeconds,relativeTimeSeconds,problem,author,programmingLanguage,verdict,testset,passedTestCount,timeConsumedMillis,memoryConsumedBytes,points,pointsInfo
0,259918877,1959,1715108158,12058,"{'contestId': 1959, 'index': 'H', 'name': 'Cou...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,157,468,9113600,NaN,NaN
4,259913982,1959,1715105175,9075,"{'contestId': 1959, 'index': 'G', 'name': 'The...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,23,390,16179200,NaN,NaN
5,259900598,1959,1715097790,1690,"{'contestId': 1959, 'index': 'F', 'name': 'Sen...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,72,328,15155200,NaN,NaN
6,259900101,1959,1715097538,1438,"{'contestId': 1959, 'index': 'E', 'name': 'Jum...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,9,281,10137600,NaN,NaN
7,259898508,1959,1715096779,679,"{'contestId': 1959, 'index': 'D', 'name': 'Tra...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,12,187,0,NaN,NaN

In [15]:
user['verdict']

0       OK
4       OK
5       OK
6       OK
7       OK
        ..
4595    OK
4596    OK
4597    OK
4604    OK
4607    OK
Name: verdict, Length: 2704, dtype: object

In [16]:
user['url'] = user['problem'].apply(lambda row: f"https://codeforces.com/problemset/problem/{row['contestId']}/{row['index']}")

In [17]:
user.head()

,id,contestId,creationTimeSeconds,relativeTimeSeconds,problem,author,programmingLanguage,verdict,testset,passedTestCount,timeConsumedMillis,memoryConsumedBytes,points,pointsInfo,url
0,259918877,1959,1715108158,12058,"{'contestId': 1959, 'index': 'H', 'name': 'Cou...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,157,468,9113600,NaN,NaN,https://codeforces.com/problemset/problem/1959/H
4,259913982,1959,1715105175,9075,"{'contestId': 1959, 'index': 'G', 'name': 'The...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,23,390,16179200,NaN,NaN,https://codeforces.com/problemset/problem/1959/G
5,259900598,1959,1715097790,1690,"{'contestId': 1959, 'index': 'F', 'name': 'Sen...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,72,328,15155200,NaN,NaN,https://codeforces.com/problemset/problem/1959/F
6,259900101,1959,1715097538,1438,"{'contestId': 1959, 'index': 'E', 'name': 'Jum...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,9,281,10137600,NaN,NaN,https://codeforces.com/problemset/problem/1959/E
7,259898508,1959,1715096779,679,"{'contestId': 1959, 'index': 'D', 'name': 'Tra...","{'contestId': 1959, 'members': [{'handle': 'to...",Kotlin 1.9,OK,TESTS,12,187,0,NaN,NaN,https://codeforces.com/problemset/problem/1959/D

In [18]:
unsolved = problems[~problems['url'].isin(user['url'])]

In [19]:
solved = problems[problems['url'].isin(user['url'])]

In [20]:
unsolved.head()

,contestId,index,name,type,tags,rating,points,url
0,1970,F3,Playing Quidditch (Hard),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F3
1,1970,F2,Playing Quidditch (Medium),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F2
2,1970,F1,Playing Quidditch (Easy),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F1
3,1970,A1,Balanced Shuffle (Easy),PROGRAMMING,"[implementation, sortings]",NaN,NaN,https://codeforces.com/problemset/problem/1970/A1
7,1967,F,Next and Prev,PROGRAMMING,"[brute force, data structures, implementation]",3200.0,3500.0,https://codeforces.com/problemset/problem/1967/F

In [21]:
solved.head()

,contestId,index,name,type,tags,rating,points,url
4,1969,F,Card Pairing,PROGRAMMING,"[dp, greedy, hashing, implementation]",3000.0,NaN,https://codeforces.com/problemset/problem/1969/F
5,1969,C,Minimizing the Sum,PROGRAMMING,"[dp, implementation]",1700.0,NaN,https://codeforces.com/problemset/problem/1969/C
6,1969,A,Two Friends,PROGRAMMING,"[constructive algorithms, implementation, math]",800.0,NaN,https://codeforces.com/problemset/problem/1969/A
8,1967,D,Long Way to be Non-decreasing,PROGRAMMING,"[binary search, dfs and similar, graphs, imple...",2800.0,1750.0,https://codeforces.com/problemset/problem/1967/D
9,1967,A,Permutation Counting,PROGRAMMING,"[binary search, greedy, implementation, math, ...",1400.0,750.0,https://codeforces.com/problemset/problem/1967/A

In [22]:
unsolved.head()

,contestId,index,name,type,tags,rating,points,url
0,1970,F3,Playing Quidditch (Hard),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F3
1,1970,F2,Playing Quidditch (Medium),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F2
2,1970,F1,Playing Quidditch (Easy),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F1
3,1970,A1,Balanced Shuffle (Easy),PROGRAMMING,"[implementation, sortings]",NaN,NaN,https://codeforces.com/problemset/problem/1970/A1
7,1967,F,Next and Prev,PROGRAMMING,"[brute force, data structures, implementation]",3200.0,3500.0,https://codeforces.com/problemset/problem/1967/F

In [23]:
unsolved.shape

(2106, 8)

In [24]:
unsolved['rating'].value_counts()

800.0     351
1200.0    159
1100.0    144
1300.0    142
1000.0    138
900.0     132
1400.0    124
1500.0    121
1600.0    113
1700.0    108
1800.0     82
1900.0     70
2000.0     61
2200.0     60
2100.0     54
2500.0     41
2300.0     39
2400.0     36
2700.0     23
2800.0     19
2600.0     15
2900.0     12
3000.0     10
3200.0      8
3500.0      8
3100.0      7
3400.0      3
3300.0      1
Name: rating, dtype: int64

In [25]:
unsolved = unsolved[['contestId', 'index', 'name', 'tags', 'rating', 'url']]

In [26]:
unsolved.head()

,contestId,index,name,tags,rating,url
0,1970,F3,Playing Quidditch (Hard),[implementation],NaN,https://codeforces.com/problemset/problem/1970/F3
1,1970,F2,Playing Quidditch (Medium),[implementation],NaN,https://codeforces.com/problemset/problem/1970/F2
2,1970,F1,Playing Quidditch (Easy),[implementation],NaN,https://codeforces.com/problemset/problem/1970/F1
3,1970,A1,Balanced Shuffle (Easy),"[implementation, sortings]",NaN,https://codeforces.com/problemset/problem/1970/A1
7,1967,F,Next and Prev,"[brute force, data structures, implementation]",3200.0,https://codeforces.com/problemset/problem/1967/F

In [27]:
unrated = unsolved[unsolved['rating'].isna()]

In [28]:
unrated.head()

,contestId,index,name,tags,rating,url
0,1970,F3,Playing Quidditch (Hard),[implementation],NaN,https://codeforces.com/problemset/problem/1970/F3
1,1970,F2,Playing Quidditch (Medium),[implementation],NaN,https://codeforces.com/problemset/problem/1970/F2
2,1970,F1,Playing Quidditch (Easy),[implementation],NaN,https://codeforces.com/problemset/problem/1970/F1
3,1970,A1,Balanced Shuffle (Easy),"[implementation, sortings]",NaN,https://codeforces.com/problemset/problem/1970/A1
21,1952,J,"Help, what does it mean to be ""Based""","[brute force, constructive algorithms, express...",NaN,https://codeforces.com/problemset/problem/1952/J

In [29]:
unsolved = unsolved[unsolved['rating'].notna()]

In [30]:
unsolved.head()

,contestId,index,name,tags,rating,url
7,1967,F,Next and Prev,"[brute force, data structures, implementation]",3200.0,https://codeforces.com/problemset/problem/1967/F
10,1966,B,Rectangle Filling,"[constructive algorithms, implementation]",1100.0,https://codeforces.com/problemset/problem/1966/B
11,1957,B,A BIT of a Construction,"[bitmasks, constructive algorithms, greedy, im...",1100.0,https://codeforces.com/problemset/problem/1957/B
12,1956,E2,Nene vs. Monsters (Hard Version),"[brute force, greedy, implementation, math]",2700.0,https://codeforces.com/problemset/problem/1956/E2
13,1956,E1,Nene vs. Monsters (Easy Version),"[brute force, implementation, math]",2500.0,https://codeforces.com/problemset/problem/1956/E1

In [31]:
import pandas as pd
import numpy as np

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
tfidf_vectorizer = TfidfVectorizer()

In [34]:
tag_vectors = tfidf_vectorizer.fit_transform(problems['tags'].apply(lambda x: ' '.join(x)))

In [35]:
def sigmoid(x, slope, midpoint):
    return 1 / (1 + np.exp(-slope * (x - midpoint)))

In [36]:
def decayed_sigmoid(x, slope, midpoint, decay_rate, weight):
    return sigmoid(x, slope, midpoint) * np.exp(-decay_rate * x / weight)

In [37]:
def label_difficulty(rating, tags, tag_vectors, tfidf_vectorizer, slope, midpoint, decay_rate, weight):
    difficulty = decayed_sigmoid(rating, slope, midpoint, decay_rate, weight)
    current_tag_vector = tfidf_vectorizer.transform([' '.join(tags)])
    cosine_similarities = (current_tag_vector * tag_vectors.T).toarray().flatten()
    tag_influence = cosine_similarities.sum() / len(cosine_similarities)
    difficulty *= (1 + tag_influence)  # Increase difficulty proportionally to tag influence
    
    if difficulty < 0.33:
        return 'Easy'
    elif difficulty < 0.66:
        return 'Medium'
    else:
        return 'Hard'

In [38]:
def segregate_problems(solved_problems, unsolved_problems, tag_vectors, tfidf_vectorizer):
    midpoint = solved_problems['rating'].median()
    slope = 0.05  
    decay_rate = 0.001 
    weight = 500

    solved_problems['difficulty'] = solved_problems.apply(
        lambda row: label_difficulty(row['rating'], row['tags'], tag_vectors, tfidf_vectorizer, slope, midpoint, decay_rate, weight),
        axis=1
    )

    unsolved_problems['difficulty'] = unsolved_problems.apply(
        lambda row: label_difficulty(row['rating'], row['tags'], tag_vectors, tfidf_vectorizer, slope, midpoint, decay_rate, weight),
        axis=1
    )

    return solved_problems, unsolved_problems

In [39]:
df_solved_labeled, df_unsolved_labeled = segregate_problems(solved, unsolved, tag_vectors, tfidf_vectorizer)

/tmp/ipykernel_11502/3299653294.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  solved_problems['difficulty'] = solved_problems.apply(

In [40]:
df_unsolved_labeled[df_unsolved_labeled['difficulty'] == 'Hard'].sample(5)

,contestId,index,name,tags,rating,url,difficulty
539,1605,E,Array Equalizer,"[binary search, greedy, implementation, math, ...",2400.0,https://codeforces.com/problemset/problem/1605/E,Hard
1004,1196,E,Connected Component on a Chessboard,"[constructive algorithms, implementation]",1800.0,https://codeforces.com/problemset/problem/1196/E,Hard
1618,725,C,Hidden Word,"[brute force, constructive algorithms, impleme...",1600.0,https://codeforces.com/problemset/problem/725/C,Hard
1461,837,E,Vasya's Function,"[binary search, implementation, math]",2100.0,https://codeforces.com/problemset/problem/837/E,Hard
1692,676,D,Theseus and labyrinth,"[graphs, implementation, shortest paths]",2000.0,https://codeforces.com/problemset/problem/676/D,Hard