In [1]:
import requests

In [2]:
req = requests.get('https://codeforces.com/api/problemset.problems?tags=implementation')

In [3]:
import pandas as pd

In [4]:
problems = pd.DataFrame(req.json()['result']['problems'])

In [5]:
problems.head()

,contestId,index,name,type,tags,points,rating
0,1970,F3,Playing Quidditch (Hard),PROGRAMMING,[implementation],NaN,NaN
1,1970,F2,Playing Quidditch (Medium),PROGRAMMING,[implementation],NaN,NaN
2,1970,F1,Playing Quidditch (Easy),PROGRAMMING,[implementation],NaN,NaN
3,1970,A1,Balanced Shuffle (Easy),PROGRAMMING,"[implementation, sortings]",NaN,NaN
4,1969,F,Card Pairing,PROGRAMMING,"[dp, greedy, implementation]",NaN,NaN

In [6]:
problems.isna().sum()

contestId      0
index          0
name           0
type           0
tags           0
points       823
rating        47
dtype: int64

In [7]:
problems[['contestId', 'index', 'name']].duplicated().sum()

0

In [8]:
problems['url'] = problems.apply(lambda row: f"https://codeforces.com/problemset/problem/{row['contestId']}/{row['index']}", axis=1)

In [9]:
problems.head()

,contestId,index,name,type,tags,points,rating,url
0,1970,F3,Playing Quidditch (Hard),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F3
1,1970,F2,Playing Quidditch (Medium),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F2
2,1970,F1,Playing Quidditch (Easy),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F1
3,1970,A1,Balanced Shuffle (Easy),PROGRAMMING,"[implementation, sortings]",NaN,NaN,https://codeforces.com/problemset/problem/1970/A1
4,1969,F,Card Pairing,PROGRAMMING,"[dp, greedy, implementation]",NaN,NaN,https://codeforces.com/problemset/problem/1969/F

In [10]:
url = "https://codeforces.com/api/user.status?handle=i_will_be_less_than_blue"
req = requests.get(url)

In [11]:
user = pd.DataFrame(req.json()['result'])

In [12]:
user.head()

,id,contestId,creationTimeSeconds,relativeTimeSeconds,problem,author,programmingLanguage,verdict,testset,passedTestCount,timeConsumedMillis,memoryConsumedBytes
0,255333318,1951,1712420845,6745,"{'contestId': 1951, 'index': 'F', 'name': 'Inv...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,98,577,7270400
1,255333119,1951,1712420816,6716,"{'contestId': 1951, 'index': 'F', 'name': 'Inv...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),WRONG_ANSWER,PRETESTS,0,15,7168000
2,255329467,1951,1712420312,6212,"{'contestId': 1951, 'index': 'F', 'name': 'Inv...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),WRONG_ANSWER,PRETESTS,0,46,7270400
3,255322404,1951,1712419409,5309,"{'contestId': 1951, 'index': 'F', 'name': 'Inv...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),WRONG_ANSWER,PRETESTS,1,61,6041600
4,255321444,1951,1712419295,5195,"{'contestId': 1951, 'index': 'F', 'name': 'Inv...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),WRONG_ANSWER,PRETESTS,1,46,4812800

In [13]:
user = user[user['verdict'] == 'OK']

In [14]:
user.head()

,id,contestId,creationTimeSeconds,relativeTimeSeconds,problem,author,programmingLanguage,verdict,testset,passedTestCount,timeConsumedMillis,memoryConsumedBytes
0,255333318,1951,1712420845,6745,"{'contestId': 1951, 'index': 'F', 'name': 'Inv...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,98,577,7270400
8,255285376,1951,1712415884,1784,"{'contestId': 1951, 'index': 'D', 'name': 'Buy...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,6,62,0
9,255276892,1951,1712415323,1223,"{'contestId': 1951, 'index': 'C', 'name': 'Tic...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,21,186,1126400
10,255266752,1951,1712414761,661,"{'contestId': 1951, 'index': 'B', 'name': 'Bat...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,13,92,102400
11,255255845,1951,1712414294,194,"{'contestId': 1951, 'index': 'A', 'name': 'Dua...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,3,46,0

In [15]:
user['verdict']

0      OK
8      OK
9      OK
10     OK
11     OK
       ..
488    OK
491    OK
493    OK
494    OK
496    OK
Name: verdict, Length: 224, dtype: object

In [16]:
user['url'] = user['problem'].apply(lambda row: f"https://codeforces.com/problemset/problem/{row['contestId']}/{row['index']}")

In [17]:
user.head()

,id,contestId,creationTimeSeconds,relativeTimeSeconds,problem,author,programmingLanguage,verdict,testset,passedTestCount,timeConsumedMillis,memoryConsumedBytes,url
0,255333318,1951,1712420845,6745,"{'contestId': 1951, 'index': 'F', 'name': 'Inv...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,98,577,7270400,https://codeforces.com/problemset/problem/1951/F
8,255285376,1951,1712415884,1784,"{'contestId': 1951, 'index': 'D', 'name': 'Buy...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,6,62,0,https://codeforces.com/problemset/problem/1951/D
9,255276892,1951,1712415323,1223,"{'contestId': 1951, 'index': 'C', 'name': 'Tic...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,21,186,1126400,https://codeforces.com/problemset/problem/1951/C
10,255266752,1951,1712414761,661,"{'contestId': 1951, 'index': 'B', 'name': 'Bat...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,13,92,102400,https://codeforces.com/problemset/problem/1951/B
11,255255845,1951,1712414294,194,"{'contestId': 1951, 'index': 'A', 'name': 'Dua...","{'contestId': 1951, 'members': [{'handle': 'i_...",C++17 (GCC 7-32),OK,TESTS,3,46,0,https://codeforces.com/problemset/problem/1951/A

In [18]:
unsolved = problems[~problems['url'].isin(user['url'])]

In [19]:
solved = problems[problems['url'].isin(user['url'])]

In [20]:
unsolved.head()

,contestId,index,name,type,tags,points,rating,url
0,1970,F3,Playing Quidditch (Hard),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F3
1,1970,F2,Playing Quidditch (Medium),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F2
2,1970,F1,Playing Quidditch (Easy),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F1
3,1970,A1,Balanced Shuffle (Easy),PROGRAMMING,"[implementation, sortings]",NaN,NaN,https://codeforces.com/problemset/problem/1970/A1
4,1969,F,Card Pairing,PROGRAMMING,"[dp, greedy, implementation]",NaN,NaN,https://codeforces.com/problemset/problem/1969/F

In [21]:
solved.head()

,contestId,index,name,type,tags,points,rating,url
39,1942,F,Farmer John's Favorite Function,PROGRAMMING,"[brute force, data structures, implementation,...",3000.0,2700.0,https://codeforces.com/problemset/problem/1942/F
40,1942,D,Learning to Paint,PROGRAMMING,"[binary search, data structures, dfs and simil...",2250.0,2100.0,https://codeforces.com/problemset/problem/1942/D
85,1916,C,Training Before the Olympiad,PROGRAMMING,"[constructive algorithms, games, greedy, imple...",1250.0,1200.0,https://codeforces.com/problemset/problem/1916/C
86,1916,A,2023,PROGRAMMING,"[constructive algorithms, implementation, math...",250.0,800.0,https://codeforces.com/problemset/problem/1916/A
132,1874,A,Jellyfish and Game,PROGRAMMING,"[brute force, games, greedy, implementation]",500.0,1200.0,https://codeforces.com/problemset/problem/1874/A

In [22]:
unsolved.head()

,contestId,index,name,type,tags,points,rating,url
0,1970,F3,Playing Quidditch (Hard),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F3
1,1970,F2,Playing Quidditch (Medium),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F2
2,1970,F1,Playing Quidditch (Easy),PROGRAMMING,[implementation],NaN,NaN,https://codeforces.com/problemset/problem/1970/F1
3,1970,A1,Balanced Shuffle (Easy),PROGRAMMING,"[implementation, sortings]",NaN,NaN,https://codeforces.com/problemset/problem/1970/A1
4,1969,F,Card Pairing,PROGRAMMING,"[dp, greedy, implementation]",NaN,NaN,https://codeforces.com/problemset/problem/1969/F

In [23]:
unsolved.shape

(2576, 8)

In [24]:
unsolved['rating'].value_counts()

800.0     401
1200.0    183
1300.0    166
1100.0    165
1000.0    160
1400.0    159
900.0     150
1500.0    144
1600.0    140
1700.0    128
1800.0    109
1900.0     93
2000.0     86
2200.0     76
2100.0     65
2500.0     56
2300.0     56
2400.0     51
2700.0     28
2800.0     26
2600.0     23
2900.0     16
3000.0     12
3500.0     11
3100.0     10
3200.0      9
3300.0      3
3400.0      3
Name: rating, dtype: int64

In [25]:
unsolved = unsolved[['contestId', 'index', 'name', 'tags', 'rating']]

In [26]:
unsolved.head()

,contestId,index,name,tags,rating
0,1970,F3,Playing Quidditch (Hard),[implementation],NaN
1,1970,F2,Playing Quidditch (Medium),[implementation],NaN
2,1970,F1,Playing Quidditch (Easy),[implementation],NaN
3,1970,A1,Balanced Shuffle (Easy),"[implementation, sortings]",NaN
4,1969,F,Card Pairing,"[dp, greedy, implementation]",NaN

In [27]:
unrated = unsolved[unsolved['rating'].isna()]

In [28]:
unrated.head()

,contestId,index,name,tags,rating
0,1970,F3,Playing Quidditch (Hard),[implementation],NaN
1,1970,F2,Playing Quidditch (Medium),[implementation],NaN
2,1970,F1,Playing Quidditch (Easy),[implementation],NaN
3,1970,A1,Balanced Shuffle (Easy),"[implementation, sortings]",NaN
4,1969,F,Card Pairing,"[dp, greedy, implementation]",NaN

In [29]:
unsolved = unsolved[unsolved['rating'].notna()]

In [30]:
unsolved.head()

,contestId,index,name,tags,rating
9,1966,B,Rectangle Filling,"[constructive algorithms, implementation]",1100.0
10,1957,B,A BIT of a Construction,"[bitmasks, constructive algorithms, greedy, im...",1100.0
11,1956,E2,Nene vs. Monsters (Hard Version),"[brute force, greedy, implementation, math]",2700.0
12,1956,E1,Nene vs. Monsters (Easy Version),"[brute force, implementation, math]",2500.0
13,1956,D,Nene and the Mex Operator,"[bitmasks, brute force, constructive algorithm...",2000.0

In [31]:
import pandas as pd
import numpy as np

In [32]:
def sigmoid(x, slope, midpoint):
    return 1 / (1 + np.exp(-slope * (x - midpoint)))

In [33]:
def decayed_sigmoid(x, slope, midpoint, decay_rate, weight):
    return sigmoid(x, slope, midpoint) * np.exp(-decay_rate * x / weight)

In [34]:
def label_difficulty(rating, slope, midpoint, decay_rate, weight):
    difficulty = decayed_sigmoid(rating, slope, midpoint, decay_rate, weight)
    if difficulty < 0.33:
        return 'Easy'
    elif difficulty < 0.66:
        return 'Medium'
    else:
        return 'Hard'

In [35]:
def segregate_problems(solved_problems, unsolved_problems):
    # Calculate midpoint, slope, decay_rate, and weight based on the rating distribution
    midpoint = solved_problems['rating'].median()
    slope = 0.05  # Adjust the slope based on the sensitivity required
    decay_rate = 0.001  # Adjust the decay rate as needed
    weight = 500  # Adjust the weight as needed

    # Apply difficulty estimation and labeling for solved problems
    solved_problems['difficulty'] = solved_problems['rating'].apply(
        lambda x: label_difficulty(x, slope, midpoint, decay_rate, weight)
    )

    # Apply difficulty estimation and labeling for unsolved problems
    unsolved_problems['difficulty'] = unsolved_problems['rating'].apply(
        lambda x: label_difficulty(x, slope, midpoint, decay_rate, weight)
    )

    return solved_problems, unsolved_problems

In [36]:
df_solved_labeled, df_unsolved_labeled = segregate_problems(solved, unsolved)

/tmp/ipykernel_5838/3643852229.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  solved_problems['difficulty'] = solved_problems['rating'].apply(

In [75]:
df_unsolved_labeled[df_unsolved_labeled['difficulty'] == 'Hard'].sample(5)

,contestId,index,name,tags,rating,difficulty
1682,679,D,Bear and Chase,"[brute force, dfs and similar, graphs, impleme...",2900.0,Hard
1292,976,D,Degree Set,"[constructive algorithms, graphs, implementation]",2500.0,Hard
155,1861,E,Non-Intersecting Subpermutations,"[combinatorics, dp, implementation, math]",2300.0,Hard
191,1837,F,Editorial for Two,"[binary search, data structures, greedy, imple...",2400.0,Hard
2110,357,B,Flag Day,"[constructive algorithms, implementation]",1400.0,Hard